### ISSUE TITLE
EPD Breakout board schematic does not match hardware

### ISSUE THREAD

**Issue by peterhinch** [adafruit/Adafruit_CircuitPython_IL0373#15]
This is probably the wrong place for this issue but I couldn't figure out where to raise it. Apologies.
[EDITED]
[This webpage](https://www.adafruit.com/product/4224) for the "eInk breakout friend" has a link to [this schematic](https://learn.adafruit.com/assets/57645). The two do not match: the schematic is of a display rather than of the breakout which is confusing. There seems to be no link to the breakout schematic itself.

**Comment by ladyada** [comment]
correct, this is the wrong place for this issue since its a software library. please post the adafruit forums

here are the eink friend schemicatics
https://learn.adafruit.com/adafruit-eink-display-breakouts/downloads#eink-friends-3050005-14
