### ISSUE TITLE
This code does not match device datasheet

### ISSUE THREAD

**Issue by peterhinch** [adafruit/Adafruit_CircuitPython_IL0373#16]
[These lines](https://github.com/adafruit/Adafruit_CircuitPython_IL0373/blob/89b14b063ca07266ba00faff8bcc07d07b713f18/adafruit_il0373.py#L175) show a 2-bit number shifted left 5 to set `RES1` and `RES0` resolution selection bits. The datasheet shows these as being D7 and D6, consequently the left shift should be 6.

**Comment by tannewt** [comment]
Nice find! Mind making a PR?

**Comment by peterhinch** [comment]
Now done https://github.com/adafruit/Adafruit_CircuitPython_IL0373/pull/18

**Comment by tannewt** [comment]
Fixed by #18. Thank you!
