### ISSUE TITLE
Code comment seems to conflict with code

### ISSUE THREAD

**Issue by peterhinch** [adafruit/Adafruit_CircuitPython_IL0373#17]
[This doc](https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/ac7829c7d96b9ebd5e473d03793e54889849cc5f/displayio/epaperdisplay.py#L90) and [this code](https://github.com/adafruit/Adafruit_CircuitPython_IL0373/blob/89b14b063ca07266ba00faff8bcc07d07b713f18/adafruit_il0373.py#L62) seem to conflict. This is of concern because it affects the Vcom voltage. I think the intention is to specify -1.0V where you may be setting -2.6V.

```python
b"\x82\x81\x12\x32"  # VCM DC and delay 50ms
```
The doc implies that the delay is the third byte (0x12 == 18ms) with a single data value in the fourth byte (0x32, which happens to equal 50). I think the code should read:
```python
b"\x82\x81\x32\x12"  # VCM DC and delay 50ms
```
The doc itself is ambiguous because it states
> When the top bit of the second byte is 1, the next byte will be the delay time in milliseconds.

This implies that the third byte is the delay time, but it then goes on to say
> The third through final bytes are the remaining command parameters.

I think that should read the fourth through final bytes, but clarification would be appreciated.

**Comment by tannewt** [comment]
The doc is incorrect. I fixed this internally but didn't realize it was here as well. See the fix here: https://github.com/adafruit/circuitpython/commit/9da99675b162742c0ecbd0995ce35e62204be3b1#diff-cd8ed509bcd7add61d99b42d41f3674916a6f91a2302914d6fd6641acf021944

**Comment by peterhinch** [comment]
Thank you, the code and code comments are therefore correct.
